Virus_Database/urls.py
from django.contrib import admin
from django.conf.urls import include, url

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('loadfile.urls', namespace="loadfile")),

]

loadfile/urls.py
from django.conf.urls import include, url

from . import views

app_name = "loadfile"

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^search/', views.search, name='search'),
    url(r'^titlerecord/', views.titlerecord, name='titlerecord'),
]

templates/base.html
<!DOCTYPE html>
{% load static %}
{% include "navbar.html" %}

<html lang="en">

  <head>
    <title>{% block title %} Virus Database {% endblock title %}</title>
    <link href="https://fonts.googleapis.com/css2?family=Roboto+Condensed:wght@400;700&display=swap" rel="stylesheet">
    <script src="{% static 'js/jquery-1.11.3.min.js' %}"></script>
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
      <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/smoothness/jquery-ui.css">
  <script src="//code.jquery.com/jquery-1.12.4.js"></script>
  <script src="//code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
    <script src="{% static 'js/chosen.jquery.min.js' %}"></script>
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css'%}">
    <link rel="stylesheet" href="{% static 'css/chosen.min.css'%}">
    <link rel="stylesheet" href="{% static 'css/main.css'%}">
    <link rel="stylesheet" href="{% static 'css/all.css'%}">

<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>

    <script src="{% static 'js/main.js' %}"></script>
    <script src="{% static 'js/all.js' %}"></script>
  {% block head %}
  {% endblock %}
  </head>

  <body>
    {% block content %}
    {% endblock %}


    <script>
      const capitalize = (s) => {
        if (typeof s !== 'string') return ''
        return s.charAt(0).toUpperCase() + s.slice(1)
      }

      function addModal(e, recordData) {

        let selectedRow = $(e.target).parents('tr');
        let recordKeys = Object.keys(recordData.object);
        let recordValues = Object.values(recordData.object)

        $("#modal-title").html(recordValues[3]);
        html = "<table class='table' align='left'><tr align='left'>"
        i = 0;
        for (key in recordData.object) {
          if (key == "id") continue
          if (i != 0 && i % 3 == 0)
            html += "</tr><tr>"
          if (key == "Genebank_ID" || key == "Version")
            recordData.object[key] = '<a target="_blank" href="https://www.ncbi.nlm.nih.gov/nuccore/' + recordData.object[key] + '">' + recordData.object[key] + '</a>'
          if (key == "Pubmed_ID" && recordData.object[key] != "NA")
            recordData.object[key] = '<a target="_blank" href="https://www.ncbi.nlm.nih.gov/pubmed/?term=' + recordData.object[key] + '">' + recordData.object[key] + '</a>'

          html += "<td style='text-align: left'><b>" + capitalize(key.replace(/_/g, ' ')) + ':</b>&nbsp;&nbsp;' + recordData.object[key] + "</td>";
          i += 1
        }
        {#if ($("#actionBtn").length >0)#}
        {#    $("#actionBtn").remove()#}
        {#$("#modal-footer").prepend("<a id='actionBtn' href='admin/loadfile/hev/"+recordData.objects.id+"/change/'><button class='btn btn-danger'>Edit</button></a>");#}
        $("#modal-body").html(html)
        $("#popUpModal").modal()
      }

           //    selectedRow.append('<!-- Modal -->' +
      //          '<div class="modal fade" id="myModal" role="dialog">' +
      //           '<div class="modal-dialog">' +
      //           '<div class="modal-content">' +
      //           '<div class="modal-header">' +
      //           '<h4 class="modal-title">'+ recordValues[3] +'</h4>' +
      //           '</div>' +
      //           '<div class="modal-body">' +
      //           '<ul class="modal-list">' +
      //           '</ul>' +
      //           '</div>' +
      //           '<div class="modal-footer">' +
      //           '<button type="button" class="btn btn-default" data-dismiss="modal">Close</button>' +
      //           '</div>' +
      //           '</div>' +
      //           '</div>' +
      //           '</div>'
      //   );
      //   let $appendedModal = $('.modal').find('ul');
      //   $.each(recordKeys, function (index, val) {
      //     $appendedModal.append(
      //             '<li><b> ' + capitalize(val.replace(/_/g,' ')) + '</b>' + recordValues[index] + '</li>'
      //     )
      //  })
      //   $("#myModal").on("hidden.bs.modal", function () {
      //     selectedRowData = [];
      //     $('#myModal').remove();
      //   });
      // }

      function showAllData(id, e) {
        $.ajax({
          method: "GET",
          dataType: "json",
          data: {"id": id},
          "url": "{% url 'loadfile:titlerecord' %}",
          success: function (data) {
            addModal(e, data);
            $('#myModal').modal('show');

          }
        })
      }
    </script>


 </body>

</html>

<!--</html>-->

templates/navbar.html
{% load static %}
<nav class="navbar navbar-expand-lg navbar-light bg-light padding-2rem">
  <a class="navbar-brand" href="{% url 'loadfile:index' %}">Virus Database</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'loadfile:index' %}">Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'loadfile:search' %}">Search</a>
      </li>
    </ul>
  </div>
</nav>